sudo: required
language:
  - objective-c
osx_image: xcode7.2
node_js:
  - 4
#before_install:
  ## Instruments fix:
  ## https://github.com/travis-ci/travis-ci/issues/4218
  #- ./test/instruments-auth.sh
before_script:
  - npm install
script:
  - _FORCE_LOGS=1 $(npm bin)/gulp e2e-test
