sudo: required
env:
  - _FORCE_LOGS=1
language:
  - node_js
osx_image: xcode7.3
node_js:
  - "0.12"
  - 4
  - 5
  - 6
# before_install:
  # Instruments fix:
  # https://github.com/travis-ci/travis-ci/issues/4218
  # - ./test/instruments-auth.sh
before_script:
  - npm install
  - npm install -g gulp
  - npm install -g mocha
script:
  - node --version
  - gulp once
  - gulp e2e-test
