sudo: required
env:
  - _FORCE_LOGS=1
language:
  - objective-c
osx_image: xcode7.3
node_js:
  - 4
#before_install:
  ## Instruments fix:
  ## https://github.com/travis-ci/travis-ci/issues/4218
  #- ./test/instruments-auth.sh
before_script:
  - npm install
  - npm install -g gulp
  - npm install -g mocha
script:
  - gulp once
  - gulp e2e-test
